(custom-set-variables
 '(Info-auto-generate-directory (quote if-outdated))
 '(Info-button1-follows-hyperlink t)
 '(Info-save-auto-generated-dir (quote always))
 '(TeX-close-quote "\"'")
 '(TeX-open-quote "\"`")
 '(all-christian-calendar-holidays t)
 '(balloon-help-background "yellow")
 '(balloon-help-mode t nil (balloon-help))
 '(balloon-help-mode-line-string " B")
 '(balloon-help-timeout 50)
 '(bar-cursor (quote (quote other)))
 '(blink-cursor-mode t nil (blink-cursor))
 '(browse-url-browser-function (quote browse-url-firefox-new-tab))
 '(browse-url-galeon-new-window-is-tab t)
 '(buffers-menu-max-size nil)
 '(c-basic-offset 4)
 '(c-default-style (quote ((java-mode . "java") (other . "gnu"))))
 '(c-echo-syntactic-information-p nil)
 '(c-label-minimum-indentation 0)
 '(c-offsets-alist (quote ((substatement-open . 0) (c . 1) (statement-block-intro . 4) (statement-case-intro . +) (statement-case-open . 0) (case-label . +) (inline-open . 0) (access-label . [0]) (brace-list-open . 0) (statement-cont . 8) (label . 0))))
 '(calc-gnuplot-name "gnuplot" t)
 '(calendar-latitude [48 8 north])
 '(calendar-longitude [11 43 east])
 '(calendar-week-start-day 1)
 '(change-log-default-name "~/ChangeLog.Work")
 '(column-number-mode t)
 '(compilation-ask-about-save nil)
 '(compilation-read-command nil)
 '(compilation-window-height 15)
 '(compile-command "NetMake -k -j9")
 '(debug-on-error nil)
 '(doxymacs-doxygen-dirs (quote (("/home/gru/projects/vxp/trunk" "/home/gru/doc/dafit/trunk/dafit.xml" "file:///home/gru/doc/dafit/trunk/html") ("/home/gru/projects/vxp/branches" "/home/gru/doc/dafit/trunk/dafit.xml" "file:///home/gru/doc/dafit/trunk/html"))))
 '(doxymacs-use-external-xml-parser t)
 '(ediff-use-toolbar-p t)
 '(efs-ftp-program-args (quote ("-i" "-n" "-g" "-v" "-p")))
 '(european-calendar-style t)
 '(find-file-compare-truenames t)
 '(gnuserv-program (concat exec-directory "/gnuserv"))
 '(gutter-buffers-tab-visible-p nil)
 '(indent-tabs-mode nil)
 '(ispell-local-dictionary "british")
 '(kill-whole-line nil)
 '(lazy-lock-stealth-time 60)
 '(line-number-mode t)
 '(make-tags-files-invisible t)
 '(mark-diary-entries-in-calendar t)
 '(mark-holidays-in-calendar t)
 '(mode-compile-always-save-buffer-p t)
 '(mode-compile-never-edit-command-p t)
 '(modifier-keys-are-sticky nil)
 '(modifier-keys-sticky-time 750 t)
 '(mouse-avoidance-mode (quote exile) nil (avoid))
 '(mouse-yank-at-point t)
 '(paren-mode (quote blink-paren) nil (paren))
 '(pending-delete-mode t nil (pending-del))
 '(printer-name "kopierer")
 '(ps-paper-type (quote a4))
 '(ps-print-color-p nil)
 '(recent-files-commands-submenu t)
 '(recent-files-dont-include (quote ("~$" "Guinan/." "INBOX" ".bbdb" ".newsrc." "places.el" "^moc_.*" "\\.cache" "TAGS")))
 '(recent-files-filename-replacements (quote (("/home/gru/projects/vxp/trunk" . "trunk") ("/mnt/ext1/home/gru" . "~") ("/home/gru" . "~") ("/home/gru/projects/vxp/branches" . "branches"))))
 '(recent-files-non-permanent-submenu nil)
 '(recent-files-number-of-entries 10)
 '(recent-files-number-of-saved-entries 10)
 '(recent-files-permanent-submenu t)
 '(recent-files-sort-function (quote recent-files-sort-alphabetically))
 '(recent-files-use-full-names t)
 '(require-final-newline (quote ask))
 '(signal-error-on-buffer-boundary nil)
 '(speedbar-directory-button-trim-method (quote trim))
 '(speedbar-directory-unshown-regexp "^\\(CVS\\|RCS\\|SCCS\\)\\'")
 '(speedbar-frame-parameters (quote ((minibuffer) (width . 36) (border-width . 0) (menu-bar-lines . 0) (tool-bar-lines . 0) (unsplittable . t))))
 '(speedbar-frame-plist (quote (minibuffer nil width 37 border-width 0 internal-border-width 0 unsplittable t default-toolbar-visible-p nil has-modeline-p nil menubar-visible-p nil default-gutter-visible-p nil)))
 '(speedbar-show-unknown-files t)
 '(speedbar-supported-extension-expressions (quote (".bnf" ".pro" ".[ch]\\(\\+\\+\\|pp\\|c\\|h\\|xx\\)?" ".tex\\(i\\(nfo\\)?\\)?" ".el" ".emacs" ".l" ".lsp" ".p" ".java" ".f\\(90\\|77\\|or\\)?" ".ada" ".p[lm]" ".tcl" ".m" ".scm" ".pm" ".py" ".s?html" "[Mm]akefile\\(\\.in\\)?")))
 '(tags-always-exact t)
 '(tags-auto-read-changed-tag-files t)
 '(tags-check-parent-directories-for-tag-files nil)
 '(tags-exuberant-ctags-optimization-p t)
 '(toolbar-visible-p nil)
 '(truncate-lines t)
 '(undo-high-threshold 300000)
 '(undo-threshold 200000)
 '(url-be-asynchronous t)
 '(url-news-server nil)
 '(url-personal-mail-address nil)
 '(url-privacy-level (quote paranoid))
 '(url-proxy-services (quote (("no_proxy" . "\\(localhost\\)") ("http" . "172.17.5.46:8000"))))
 '(url-show-status nil)
 '(url-use-hypertext-gopher nil)
 '(vc-mode-face (quote highlight))
 '(visible-bell t)
 '(vvb-column 100 t)
 '(vvb-mode t t)
 '(vvb-right-on-eol-p t t)
 '(w3-default-homepage "file:///home/gru/doc/dafit/1.50/html/index.html")
 '(w3-delay-image-loads t)
 '(w3-do-incremental-display t)
 '(w3-icon-format nil)
 '(w3-maximum-line-length 100)
 '(w3-min-img-size 5)
 '(whitespace-auto-cleanup t))
(custom-set-faces
 '(default ((t (:size "13pt" :family nil :background-pixmap "~/.xemacs/my/marble.png"))) t)
 '(diary-face ((t (:foreground "yellow" :background "blue" :bold t))) t)
 '(dired-face-header ((t (:foreground "black" :bold t))))
 '(dired-face-permissions ((((type x pm mswindows) (class color)) (:foreground "blue"))))
 '(dired-face-symlink ((((type x pm mswindows) (class color) (background light)) (:foreground "navy"))))
 '(flyspell-duplicate-face ((((class color)) (:italic nil :underline t))))
 '(flyspell-incorrect-face ((((class color)) (:underline t))))
 '(highlight ((t (:background "darkseagreen2" :size "9"))) t)
 '(isearch ((t (:foreground "yellow" :background "red"))) t)
 '(modeline ((t (:background "Gray80" :size "9"))) t)
 '(modeline-buffer-id ((t (:foreground "blue4" :background "Gray80" :size "9"))) t)
 '(primary-selection ((t (:background "LightSkyBlue1"))) t)
 '(text-cursor ((t (:foreground "white" :background "Blue"))) t)
 '(vc-annotate-face-00FF31 ((t (:foreground "#6a5acd" :background ""))) t)
 '(vc-annotate-face-00FFD9 ((t (:foreground "#32cd32" :background ""))) t)
 '(vc-annotate-face-07FF00 ((t (:foreground "red" :background ""))) t)
 '(vc-annotate-face-AFFF00 ((t (:foreground "#8b6508"))) t)
 '(vc-annotate-face-FFE000 ((t (:foreground "magenta2"))) t)
 '(vvb-face ((t (:foreground "white" :background "Red3"))) t)
 '(zmacs-region ((t (:background "LightSkyBlue1"))) t))
(put 'narrow-to-region 'disabled nil)
